quovadisapp/urls.py
from django.urls import path
from . import views

app_name = 'quovadisapp'
urlpatterns = [
    path('about/', views.about, name='about'),
    path('activities/', views.activities, name='activities'),
    path('contact/', views.contact, name='contact'),
    path('rooms/', views.rooms, name='rooms'),
    path('rooms/<int:room_id>/', views.room_detail, name='room_detail'),
    path('restaurant/', views.restaurant, name='restaurant'),
]

quovadisproject/urls.py
from django.contrib import admin
from django.urls import include, path

from quovadisapp.views import index

urlpatterns = [
    path('', index, name='index'),
    path('qv/', include('quovadisapp.urls')),
    path('admin/', admin.site.urls),
]

quovadisapp/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from cloudinary.models import CloudinaryField


class Room(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.IntegerField(default=0)
    services = ArrayField(models.CharField(max_length=100, blank=True))

    def __str__(self):
        return "%s" % (self.name)


class RoomImage(models.Model):
    tag = models.CharField(max_length=100)
    image = CloudinaryField('image')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="images")

    def primary_image(self):
        pass

    def gallery_image(self):
        pass


class SliderImage(models.Model):
    tag = models.CharField(max_length=100)
    image = CloudinaryField('image')
    text = models.CharField(max_length=200, default="Welcome to Quo Vadis")
    sub_text = models.TextField(max_length=300, default="Luxury Boutique Hotel")

    def __str__(self):
        return "%s" % (self.tag)


class Activity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    image = CloudinaryField('image', default="img/logo.png")

    def __str__(self):
        return "%s" % (self.name)


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)

    def __str__(self):
        return "%s" % (self.name)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return "%s" % (self.name)


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500, default=None, blank=True, null=True)
    price = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="menu")

    def __str__(self):
        return "%s" % (self.name)

quovadisproject/quovadisapp/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from cloudinary.models import CloudinaryField


class Room(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.IntegerField(default=0)
    services = ArrayField(models.CharField(max_length=100, blank=True))

    def __str__(self):
        return "%s" % (self.name)


class RoomImage(models.Model):
    tag = models.CharField(max_length=100)
    image = CloudinaryField('image')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="images")

    def primary_image(self):
        pass

    def gallery_image(self):
        pass


class SliderImage(models.Model):
    tag = models.CharField(max_length=100)
    image = CloudinaryField('image')
    text = models.CharField(max_length=200, default="Welcome to Quo Vadis")
    sub_text = models.TextField(max_length=300, default="Luxury Boutique Hotel")

    def __str__(self):
        return "%s" % (self.tag)


class Activity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    image = CloudinaryField('image', default="img/logo.png")

    def __str__(self):
        return "%s" % (self.name)


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)

    def __str__(self):
        return "%s" % (self.name)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return "%s" % (self.name)


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.IntegerField(default=0)
    category = models.OneToOneField(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % (self.name)

quovadisapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import SliderImage, Activity, Service, Room, Category


# Create your views here.


def index(request):
    images = SliderImage.objects.all()
    main_image = None
    for image in images:
        if image.tag == 'main':
            main_image = image
            images = SliderImage.objects.exclude(tag='main')
            break

    room_info = {}
    rooms = Room.objects.all()
    for room in rooms[:3]:
        room_info[room.name] = [room, room.images.all()[0]]

    context = {
        "main_image": main_image,
        "secondary_images": images,
        "room_info": room_info
    }
    return render(request, 'quovadisapp/index.html', context)


def about(request):
    services = Service.objects.all()
    if len(services) > 8:
        services = services[:8]

    context = {"services": services}

    return render(request, 'quovadisapp/about.html', context)


def activities(request):
    activities = Activity.objects.all()
    context = {"activities": activities}
    return render(request, 'quovadisapp/activities.html', context)


def rooms(request):
    room_info = {}
    rooms = Room.objects.all()
    for room in rooms:
        room_info[room.name] = [room, room.images.all()]
    context = {"room_info": room_info}
    return render(request, 'quovadisapp/rooms.html', context)


def room_detail(request, room_id):
    room = Room.objects.get(id=room_id)
    room_info = [room, room.images.all()]
    context = {"room_info": room_info}
    return render(request, 'quovadisapp/detail.html', context)


def restaurant(request):
    breakfast = []
    lunch = []
    dinner = []
    categories = Category.objects.all()
    for category in categories:
        if category.name == "Breakfast":
            breakfast = category.menu.all()
        elif category.name == "Lunch":
            lunch = category.menu.all()
        elif category.name == "Dinner":
            dinner = category.menu.all()

    context = {"breakfast": breakfast, "lunch": lunch, "dinner": dinner}
    return render(request, 'quovadisapp/restaurant.html', context)


def contact(request):
    return render(request, 'quovadisapp/contact.html')

quovadisproject/quovadisapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import SliderImage, Activity, Service, Room


# Create your views here.


def index(request):
    images = SliderImage.objects.all()
    main_image = None
    for image in images:
        if image.tag == 'main':
            main_image = image
            images = SliderImage.objects.exclude(tag='main')
            break

    context = {
        "main_image": main_image,
        "secondary_images": images
    }
    return render(request, 'quovadisapp/index.html', context)


def about(request):
    services = Service.objects.all()
    if len(services) > 8:
        services = services[:8]

    context = {"services": services}

    return render(request, 'quovadisapp/about.html', context)


def activities(request):
    activities = Activity.objects.all()
    context = {"activities": activities}
    return render(request, 'quovadisapp/activities.html', context)


def rooms(request):
    rooms = Room.objects.all()
    context = {"rooms": rooms}
    return render(request, 'quovadisapp/rooms.html', context)


def room_detail(request, room_id):
    return render(request, 'quovadisapp/detail.html')


def restaurant(request):
    return render(request, 'quovadisapp/restaurant.html')


def contact(request):
    return render(request, 'quovadisapp/contact.html')

quovadisapp/templates/quovadisapp/about.html
{% extends 'quovadisapp/layout/base.html' %}
{% load static %}
{% block content %}
    <body class="about">
        <!--================Header Area =================-->
        {% include 'quovadisapp/partials/header.html' %}
        <!--================Header Area =================-->
        
        <!--================Banner Area =================-->
        <section class="banner_area about_banner">
            <div class="container">
                <div class="banner_inner_content">
                    <h3>About Us</h3>
                </div>
            </div>
        </section>
        <!--================End Banner Area =================-->
        
        <!--================Resort Story Area =================-->
        <section class="introduction_area resort_story_area">
            <div class="container">
                <div class="row introduction_inner">
                    <div class="col-md-5">
                        <a href="#" class="introduction_img">
                            <img src="{% static 'img/about.jpg' %}" alt="">
                        </a>
                    </div>
                    <div class="col-md-7">
                        <div class="introduction_left_text">
                            <div class="resort_title">
                                <h2>Hotel <span>Quo Vadis</span></h2>
                                <h5></h5>
                            </div>
                            <h6>Hotel Quo Vadis promises a departure from the typical hotel room</h6>

                            <p>
                                Hotel Quo Vadis brings you into the world of chic design, attention to detail and luxury.
                                We offer a variety of rooms to our guests, from cozy singles and deluxe doubles to
                                sumptuous suites. All of our rooms come with complimentary drinks, premium
                                cable tv with a selection of over 250 channels and free high-speed wireless Internet.
                            </p>
                            <a class="about_btn_b" href="{% url 'quovadisapp:contact' %}">contact us</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Resort Story Area =================-->
        
        <!--================Choose Resot Area =================-->
        <section class="choose_resot_area">
            <div class="container">
                <div class="center_title">
                    <h2>why <span>Us?</span></h2>
                    <p>Why choose Hotel Quo Vadis?</p>
                </div>
                <div class="row choose_resot_inner">
                    <div class="col-md-5">
                        <div class="resot_list">
                            <ul>
                                {% for service in services %}
                                    <li><a><i class="fa fa-caret-right" aria-hidden="true"></i>{{service}}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="choose_resot_slider owl-carousel">
                            <div class="item">
                                <img src="{% static 'img/about/gallery-01.jpg' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'img/about/gallery-02.jpg' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'img/about/gallery-03.jpg' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'img/about/gallery-04.jpg' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'img/about/gallery-05.jpg' %}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Choose Resot Area =================-->

        <!--================End Fun Fact Area =================-->
        {% include 'quovadisapp/partials/footer.html' %}
    </body>
{% endblock content %}

quovadisapp/templates/quovadisapp/detail.html
{% extends 'quovadisapp/layout/base.html' %}
{% load static %}
{% load quovadis_extras %}

{% block content %}
    <body class="detail">

        <!--================Header Area =================-->
        {% include 'quovadisapp/partials/header.html' %}
        <!--================Header Area =================-->
        
        <!--================Banner Area =================-->
        <section class="banner_area">
            <div class="container">
                <div class="banner_inner_content">
                    <h3>Room Details</h3>
                </div>
            </div>
        </section>
        <!--================End Banner Area =================-->
        
        <!--================Search Room Area =================-->
        <section class="room_details_area">
            <div class="container">
                <div class="row room_details_inner">
                    <div class="col-md-8">
                        <div class="room_details_content">
                            <div class="room_d_main_text">
                                <div class="room_details_img owl-carousel">
                                    {% for room_image in room_info.1 %}
                                        <div class="item">
                                            <img src="{{ room_image.image.url }}" class="room-img" alt="">
                                         </div>
                                    {% endfor %}
                                </div>
                                <a>
                                    <h4>{{ room_info.0.name|split_space:0 }}
                                        <span>{{ room_info.0.name|split_space:1  }}</span>
                                    </h4>
                                </a>
                                <h5>${{ room_info.0.price|format_price }} <span>/ Night</span></h5>
                                <p>{{ room_info.0.description }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="search_right_sidebar">
                            <div class="book_room_area">
                                <div class="book_room_box">
                                    <div class="book_table_item">
                                        <h3>Make a Reservation</h3>
                                    </div>
                                    <div class="book_table_item">
                                         <div class="media-left">
                                            <i class="fa fa-envelope-o fa-2x"></i>
                                        </div>
                                        <div class="media-body">
                                            <a href="mailto:info@hotelquovadisng.com"
                                               style="color: #bd7e5e;"
                                            >
                                                info@hotelquovadisng.com
                                            </a>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="book_table_item">
                                        <div class="media-left">
                                            <i class="fa fa-phone fa-2x"></i>
                                        </div>
                                        <div class="media-body">
                                            <h4>+ (234) 92 918 113</h4>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="book_table_item">
                                        <div class="media-left">
                                            <i class="fa fa-map-marker fa-2x"></i>
                                        </div>
                                        <div class="media-body">
                                            <p>
                                                <h4>4, Tarkwa Close, Off Monrovia Street <br /> <br />
                                                Wuse 2, Abuja, Nigeria
                                                </h4>
                                            </p>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="book_table_item">
                                        <a class="book_now_btn" href="{% url 'quovadisapp:contact' %}">Reserve now</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Search Room Area =================-->
        
       {% include 'quovadisapp/partials/footer.html' %}
    </body>
{% endblock content%}

quovadisapp/templates/quovadisapp/partials/footer.html
 {%load static%}
 <!--================Footer Area =================-->
        <footer class="footer_area">
            <div class="footer_widget_area">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-xs-6">
                            <aside class="f_widget about_widget">
                                <img src="{% static 'img/logo_sticky.png' %}" alt="Logo">
                                <div class="ab_wd_list">
                                    <div class="media">
                                        <div class="media-left">
                                            <i class="fa fa-map-marker"></i>
                                        </div>
                                        <div class="media-body">
                                            <h4>4, Tarkwa Close, Off Monrovia Street, Abuja, Nigeria</h4>
                                        </div>
                                    </div>
                                    <div class="media">
                                        <div class="media-left">
                                            <i class="fa fa-phone"></i>
                                        </div>
                                        <div class="media-body">
                                            <h4>+ (234) 92 918 113</h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="book_now_area">
                                    <a class="book_now_btn" href="{% url 'quovadisapp:contact' %}">Book now</a>
                                </div>
                            </aside>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <aside class="f_widget link_widget">
                                <div class="f_title">
                                    <h3>Navigation</h3>
                                </div>
                                <ul>
                                    <li><a href="{% url 'quovadisapp:rooms' %}">Rooms</a></li>
                                    <li><a href="{% url 'quovadisapp:activities' %}">Activities</a></li>
                                    <li><a href="{% url 'quovadisapp:restaurant' %}">VII Bistro</a></li>
                                    <li><a href="{% url 'quovadisapp:about' %}">About</a></li>
                                    <li><a href="{% url 'quovadisapp:contact' %}">Contact</a></li>
                                </ul>
                            </aside>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <aside class="f_widget link_widget">
                                <div class="f_title">
                                    <h3>Why us?</h3>
                                </div>
                                <ul>
                                    <li><a>Free High Speed Wifi</a></li>
                                    <li><a>Free Breakfast</a></li>
                                    <li><a>Car Rental</a></li>
                                    <li><a>Meeting Room</a></li>
                                    <li><a href="{% url 'quovadisapp:about' %}">View more</a></li>
                                </ul>
                            </aside>
                        </div>
                        <!--<div class="col-md-3 col-xs-6">-->
                            <!--<aside class="f_widget instagram_widget">-->
                                <!--<div class="f_title">-->
                                    <!--<h3>Instagram</h3>-->
                                <!--</div>-->
                                <!--<ul class="instagram_list" id="instafeed"></ul>-->
                            <!--</aside>-->
                        <!--</div>-->
                    </div>
                </div>
            </div>
            <div class="footer_copyright_area">
                <div class="container">
                    <div class="pull-left">
                        <h4>Copyright © Hotel Quo Vadis  <script>document.write(new Date().getFullYear());</script>. All rights reserved. </h4>
                    </div>
                </div>
            </div>
        </footer>
        <!--================End Footer Area =================-->
        
        <!--================Search Box Area =================-->
        <div class="search_area zoom-anim-dialog mfp-hide" id="test-search">
            <div class="search_box_inner">
                <h3>Search</h3>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><i class="icon icon-Search"></i></button>
                    </span>
                </div>
            </div>
        </div>
        <!--================End Search Box Area =================-->
        <!--================End Footer Area =================-->

quovadisapp/templates/quovadisapp/partials/header.html
{%load static%}
<header class="main_header_area">
    <div class="header_top">
        <div class="container">
            <div class="header_top_inner">
                <div class="pull-left">
                    <a href="#"><i class="fa fa-phone"></i>+ (234) 92 918 113</a>
                    <a href="#"><i class="fa fa-envelope-o"></i>info@hotelquovadisng.com</a>
                </div>
                <div class="pull-right">
                    <!-- <ul class="header_social">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul> -->
                </div>
            </div>
        </div>
    </div>
    <div class="header_menu">
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'index' %}">
                        <img src="{% static 'img/logo.png' %}" alt="Logo">
                        <img src="{% static 'img/logo.png' %}" alt="Logo">
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
<!--                         <li class="index"><a href="{% url 'index' %}">Home</a></li>
 -->                        <li class="rooms"><a href="{% url 'quovadisapp:rooms' %}">Rooms</a></li>
                        <li class="activities"><a href="{% url 'quovadisapp:activities' %}">Activities</a></li>
                        <li class="restaurant"><a href="{% url 'quovadisapp:restaurant' %}">Restaurant &amp; Bar</a></li>
                        <li class="about"><a href="{% url 'quovadisapp:about' %}">About</a></li>
                        <li class="contact"><a href="{% url 'quovadisapp:contact' %}">Contact</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
</header>

quovadisapp/templates/quovadisapp/partials/header_top.html
<div class="header_top">
    <div class="container">
        <div class="header_top_inner">
            <div class="pull-left">
                <a href="#"><i class="fa fa-phone"></i>+ (234) 92 918 113</a>
                <a href="#"><i class="fa fa-envelope-o"></i>info@hotelquovadisng.com</a>
            </div>
            <div class="pull-right">
                <!-- <ul class="header_social">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul> -->
            </div>
        </div>
    </div>
</div>

quovadisproject/quovadisapp/templates/quovadisapp/partials/header.html
{%load static%}
<header class="main_header_area">
    <div class="header_top">
        <div class="container">
            <div class="header_top_inner">
                <div class="pull-left">
                    <a href="#"><i class="fa fa-phone"></i>+ (234) 92 918 113</a>
                    <a href="#"><i class="fa fa-envelope-o"></i>info@hotelquovadisng.com</a>
                </div>
                <div class="pull-right">
                    <ul class="header_social">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="header_menu">
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="" alt="Logo">
                        <img src="{% static 'img/logo-sticky.gif' %}" alt="">
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'quovadisapp:rooms' %}">Rooms</a></li>
                        <li><a href="{% url 'quovadisapp:activities' %}">Activities</a></li>
                        <li><a href="{% url 'quovadisapp:restaurant' %}">Restaurant &amp; Bar</a></li>
                        <li><a href="{% url 'quovadisapp:about' %}">About</a></li>
                        <li><a href="{% url 'quovadisapp:contact' %}">Contact</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
</header>